language: c

install: 
  - git clone https://github.com/Flyy-y/util.git $HOME/util
  - $HOME/util/bin/gen_makefile config/libft.json
  - $HOME/util/bin/gen_makefile config/libft.json > Makefile
  - make

script:
  - $HOME/util/bin/gen_makefile config/hmap_test.json > tests/hmap/Makefile
  - cd tests/hmap
  - make
  - ./hmap_test.out $(( $RANDOM*3 ))

os:
  - linux

compiler:
  - clang
  - gcc

git:
  dept: false