language: c

install: 
  - git clone https://github.com/Flyy-y/util.git $HOME/util
  - $HOME/util/bin/gen_makefile config/libft.json Makefile
  - make

script:
  - cd tests/hmap
  - $HOME/util/bin/gen_makefile ../config/hmap_test.json Makefile
  - make
  - ./hmap_test.out $(( $RANDOM*3 ))

os:
  - linux

compiler:
  - clang
  - gcc

git:
  dept: false