language: c

install: 
  - git clone https://github.com/Flyy-y/util.git $HOME/util
  - $HOME/util/bin/gen_makefile config.json > Makefile

script: make

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

git:
  dept: false